 Q1. Write a Python Program to Add Two Matrices?


In [ ]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
 
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
# iterate through rows
for i in range(len(X)):  
# iterate through columns
    for j in range(3):
        result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


2. Write a Python Program to Multiply Two Matrices?


In [ ]:
import numpy as np

A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 

B = [[5, 8, 1],
    [6, 7, 3],
    [4, 5, 9]]
 

 
result= [[0,0,0,],
        [0,0,0],
        [0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60]
[74 97 73]
[119 157 112]


3. Write a Python Program to Transpose a Matrix?

In [2]:
x = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

result = [[0,0,0,],
        [0,0,0],
        [0,0,0]]

for i in  range(len(x)):

   for j in range(len(x[0])):
       result[j][i] = x[i][j]

for r in result:
  print(r)

[12, 4, 7]
[7, 5, 8]
[3, 6, 9]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
s = str(input("enter the sentence"))
W = s.split(" ")
for i in range(len(W)):
   W[i]=W[i].lower()

ba = sorted(W)

print(' '.join(ba))


enter the sentenceGolu tHE ChOR 
 chor golu the


Write a Python Program to Remove Punctuation From a String?

In [2]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

st = str(input("Enter the string"))

No_punt= ' '

for i in st:

  if i not in punctuations:
    No_punt = No_punt + i



print(No_punt)

Enter the stringHello!!!, he said ---and went.
 Hello he said and went
